# .github/workflows/ai-summary.yml
name: Generate PR Summary

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  summarize:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # Required to post comments
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Generate Summary
        uses: KimTaeYang92/git-diff@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          gemini-api-key: ${{ secrets.GEMINI_API_KEY }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          ai-provider: 'gemini'
